export const AUDIT_LOG_ACTIONS = {
  bulkUpdate: 'BULK_UPDATE',
  bulkDelete: 'BULK_DELETE',
  loginAttempt: 'LOGIN_ATTEMPT',
  login: 'LOGIN',
  logout: 'LOGOUT',
  notificationsRead: 'NOTIFICATIONS_READ',
  accountTypeCreate: 'ACCOUNT_TYPE_CREATE',
  accountTypeUpdate: 'ACCOUNT_TYPE_UPDATE',
  accountTypeDelete: 'ACCOUNT_TYPE_DELETE',
  userProfileCreate: 'USER_PROFILE_CREATE',
  userProfileUpdate: 'USER_PROFILE_UPDATE',
  personnelCreate: 'PERSONNEL_CREATE',
  personnelUpdate: 'PERSONNEL_UPDATE',
  personnelDelete: 'PERSONNEL_DELETE',
  rankCreate: 'RANK_CREATE',
  rankDelete: 'RANK_DELETE',
  battalionCreate: 'BATTALION_CREATE',
  battalionUpdate: 'BATTALION_UPDATE',
  battalionDelete: 'BATTALION_DELETE',
  companyCreate: 'COMPANY_CREATE',
  companyUpdate: 'COMPANY_UPDATE',
  companyDelete: 'COMPANY_DELETE',
  trainingCreate: 'TRAINING_CREATE',
  trainingUpdate: 'TRAINING_UPDATE',
  trainingDelete: 'TRAINING_DELETE',
  trainingRecordCreate: 'TRAINING_RECORD_CREATE',
  trainingRecordUpdate: 'TRAINING_RECORD_UPDATE',
  trainingRecordDelete: 'TRAINING_RECORD_DELETE',
  trainingCategoryCreate: 'TRAINING_CATEGORY_CREATE',
  trainingCategoryUpdate: 'TRAINING_CATEGORY_UPDATE',
  trainingCategoryDelete: 'TRAINING_CATEGORY_DELETE',
  deploymentCreate: 'DEPLOYMENT_CREATE',
  deploymentRecordCreate: 'DEPLOYMENT_RECORD_CREATE',
  deploymentRecordUpdate: 'DEPLOYMENT_RECORD_UPDATE',
  deploymentRecordDelete: 'DEPLOYMENT_RECORD_DELETE',
  deploymentUpdate: 'DEPLOYMENT_UPDATE',
  deploymentDelete: 'DEPLOYMENT_DELETE',
  engagementCreate: 'ENGAGEMENT_CREATE',
  engagementUpdate: 'ENGAGEMENT_UPDATE',
  engagementDelete: 'ENGAGEMENT_DELETE',
  engagementRecordCreate: 'ENGAGEMENT_RECORD_CREATE',
  engagementRecordUpdate: 'ENGAGEMENT_RECORD_UPDATE',
  engagementRecordDelete: 'ENGAGEMENT_RECORD_DELETE',
  equipmentCategoryCreate: 'EQUIPMENT_CATEGORY_CREATE',
  equipmentCategoryUpdate: 'EQUIPMENT_CATEGORY_UPDATE',
  equipmentCategoryDelete: 'EQUIPMENT_CATEGORY_DELETE',
  equipmentItemCreate: 'EQUIPMENT_ITEM_CREATE',
  equipmentItemUpdate: 'EQUIPMENT_ITEM_UPDATE',
  equipmentItemDelete: 'EQUIPMENT_ITEM_DELETE',
  equipmentAssetCreate: 'EQUIPMENT_ASSET_CREATE',
  equipmentAssetUpdate: 'EQUIPMENT_ASSET_UPDATE',
  equipmentAssetDelete: 'EQUIPMENT_ASSET_DELETE',
  equipmentIssuanceCreate: 'EQUIPMENT_ISSUANCE_CREATE',
  equipmentIssuanceUpdate: 'EQUIPMENT_ISSUANCE_UPDATE',
  equipmentIssuanceDelete: 'EQUIPMENT_ISSUANCE_DELETE',
  equipmentIncidentCreate: 'EQUIPMENT_INCIDENT_CREATE',
  equipmentIncidentUpdate: 'EQUIPMENT_INCIDENT_UPDATE',
  equipmentIncidentDelete: 'EQUIPMENT_INCIDENT_DELETE',
  fileAttachmentCreate: 'FILE_ATTACHMENT_CREATE',
  applicationSettingsUpdate: 'APPLICATION_SETTINGS_UPDATE',
  dataTablePrint: 'DATA_TABLE_PRINT',
  backupDownload: 'BACKUP_DOWNLOAD',
} as const

export const AUDIT_LOG_OUTCOMES = {
  success: 'success',
  failed: 'failed',
} as const

export const AUDIT_LOG_SEARCHABLE_FIELD_COLUMNS = Object.freeze({
  action: 'action',
  tableName: 'table_name',
  recordId: 'record_id',
  ipAddress: 'ip_address',
  statusCode: 'status_code',
  userName: 'user_profiles.full_name',
  createdAt: 'created_at',
})

export const AUDIT_LOG_LEGACY_SEARCH_FIELDS = Object.freeze([
  'action',
  'tableName',
  'recordId',
  'ipAddress',
  'statusCode',
] as const)

export const AUDIT_LOG_ENDPOINTS = {
  domainBulkUpdate: '/api/:domain/bulk',
  domainBulkDelete: '/api/:domain/bulk',
  authLogin: '/api/auth/login',
  authLogout: '/api/auth/logout',
  notificationsRead: '/api/notifications/read',
  accountTypesCreate: '/api/account-types',
  accountTypesUpdate: '/api/account-types/:id',
  accountTypesDelete: '/api/account-types/:id',
  userProfilesCreate: '/api/users',
  userProfilesUpdate: '/api/users/:id',
  userProfilesPasswordUpdate: '/api/users/:id/password',
  userProfilesActivationUpdate: '/api/users/:id/activation',
  personnelCreate: '/api/personnel',
  personnelBatchUpload: '/api/personnel/batch-upload',
  personnelUpdate: '/api/personnel/:id',
  personnelDelete: '/api/personnel/:id',
  personnelAssignTrainingRecord: '/api/personnel/:id/training-record',
  personnelAssignDeploymentRecord: '/api/personnel/:id/deployment-record',
  personnelAssignEngagementRecord:'/api/personnel/:id/engagement-record',
  ranksCreate: '/api/ranks',
  ranksDelete: '/api/ranks/:id',
  battalionsCreate: '/api/battalions',
  battalionsUpdate: '/api/battalions/:id',
  battalionsDelete: '/api/battalions/:id',
  companiesCreate: '/api/companies',
  companiesUpdate: '/api/companies/:id',
  companiesDelete: '/api/companies/:id',
  trainingsCreate: '/api/trainings',
  trainingsUpdate: '/api/trainings/:id',
  trainingsDelete: '/api/trainings/:id',
  trainingRecordsCreate: '/api/training-records',
  trainingRecordsUpdate: '/api/training-records/:id',
  trainingRecordsDelete: '/api/training-records/:id',
  trainingCategoriesCreate: '/api/training-categories',
  trainingCategoriesUpdate: '/api/training-categories/:id',
  trainingCategoriesDelete: '/api/training-categories/:id',
  deploymentsCreate: '/api/deployments',
  deploymentsUpdate: '/api/deployments/:id',
  deploymentsDelete: '/api/deployments/:id',
  deploymentRecordsCreate: '/api/deployment-records',
  deploymentRecordsUpdate: '/api/deployment-records/:id',
  deploymentRecordsDelete: '/api/deployment-records/:id',
  engagementsCreate: '/api/engagements',
  engagementsUpdate: '/api/engagements/:id',
  engagementsDelete: '/api/engagements/:id',
  engagementRecordsCreate: '/api/engagement-records',
  engagementRecordsUpdate: '/api/engagement-records/:id',
  engagementRecordsDelete: '/api/engagement-records/:id',
  equipmentCategoriesCreate: '/api/equipment-categories',
  equipmentCategoriesUpdate: '/api/equipment-categories/:id',
  equipmentCategoriesDelete: '/api/equipment-categories/:id',
  equipmentItemsCreate: '/api/equipment-items',
  equipmentItemsUpdate: '/api/equipment-items/:id',
  equipmentItemsDelete: '/api/equipment-items/:id',
  equipmentAssetsCreate: '/api/equipment-assets',
  equipmentAssetsUpdate: '/api/equipment-assets/:id',
  equipmentAssetsDelete: '/api/equipment-assets/:id',
  equipmentIssuancesCreate: '/api/equipment-issuances',
  equipmentIssuancesUpdate: '/api/equipment-issuances/:id',
  equipmentIssuancesDelete: '/api/equipment-issuances/:id',
  equipmentIncidentsCreate: '/api/incidents',
  equipmentIncidentsDetailsUpdate: '/api/incidents/:id/details',
  equipmentIncidentsEquipmentUpdate: '/api/incidents/:id/equipment',
  equipmentIncidentsPersonnelUpdate: '/api/incidents/:id/personnel',
  equipmentIncidentsDeploymentUpdate: '/api/incidents/:id/deployment',
  equipmentIncidentsLocationUpdate: '/api/incidents/:id/location',
  equipmentIncidentsStatusUpdate: '/api/incidents/:id/status',
  equipmentIncidentsDelete: '/api/incidents/:id',
  applicationSettingsUpdate: '/api/application-settings',
  fileUpload: '/api/files/upload',
  auditPrint: '/api/audit/print',
  backupDownload: '/api/backups/download',
} as const
