export const AUDIT_LOG_ACTIONS = {
  loginAttempt: 'LOGIN_ATTEMPT',
  login: 'LOGIN',
  logout: 'LOGOUT',
  accountTypeCreate: 'ACCOUNT_TYPE_CREATE',
  accountTypeUpdate: 'ACCOUNT_TYPE_UPDATE',
  accountTypeDelete: 'ACCOUNT_TYPE_DELETE',
  userProfileCreate: 'USER_PROFILE_CREATE',
  userProfileUpdate: 'USER_PROFILE_UPDATE',
  personnelCreate: 'PERSONNEL_CREATE',
  personnelUpdate: 'PERSONNEL_UPDATE',
  personnelDelete: 'PERSONNEL_DELETE',
  rankCreate: 'RANK_CREATE',
  rankDelete: 'RANK_DELETE',
  battalionCreate: 'BATTALION_CREATE',
  battalionUpdate: 'BATTALION_UPDATE',
  battalionDelete: 'BATTALION_DELETE',
  companyCreate: 'COMPANY_CREATE',
  companyUpdate: 'COMPANY_UPDATE',
  companyDelete: 'COMPANY_DELETE',
  trainingCreate: 'TRAINING_CREATE',
  trainingUpdate: 'TRAINING_UPDATE',
  trainingDelete: 'TRAINING_DELETE',
  trainingRecordCreate: 'TRAINING_RECORD_CREATE',
  trainingRecordUpdate: 'TRAINING_RECORD_UPDATE',
  trainingRecordDelete: 'TRAINING_RECORD_DELETE',
  trainingCategoryCreate: 'TRAINING_CATEGORY_CREATE',
  trainingCategoryUpdate: 'TRAINING_CATEGORY_UPDATE',
  trainingCategoryDelete: 'TRAINING_CATEGORY_DELETE',
  deploymentCreate: 'DEPLOYMENT_CREATE',
  deploymentRecordCreate: 'DEPLOYMENT_RECORD_CREATE',
  deploymentRecordUpdate: 'DEPLOYMENT_RECORD_UPDATE',
  deploymentRecordDelete: 'DEPLOYMENT_RECORD_DELETE',
  deploymentUpdate: 'DEPLOYMENT_UPDATE',
  deploymentDelete: 'DEPLOYMENT_DELETE',
  engagementCreate: 'ENGAGEMENT_CREATE',
  engagementUpdate: 'ENGAGEMENT_UPDATE',
  engagementDelete: 'ENGAGEMENT_DELETE',
  fileAttachmentCreate: 'FILE_ATTACHMENT_CREATE',
} as const

export const AUDIT_LOG_OUTCOMES = {
  success: 'success',
  failed: 'failed',
} as const

export const AUDIT_LOG_ENDPOINTS = {
  authLogin: '/api/auth/login',
  authLogout: '/api/auth/logout',
  accountTypesCreate: '/api/account-types',
  accountTypesUpdate: '/api/account-types/:id',
  accountTypesDelete: '/api/account-types/:id',
  userProfilesCreate: '/api/users',
  userProfilesUpdate: '/api/users/:id',
  userProfilesPasswordUpdate: '/api/users/:id/password',
  userProfilesActivationUpdate: '/api/users/:id/activation',
  personnelCreate: '/api/personnel',
  personnelBatchUpload: '/api/personnel/batch-upload',
  personnelUpdate: '/api/personnel/:id',
  personnelDelete: '/api/personnel/:id',
  ranksCreate: '/api/ranks',
  ranksDelete: '/api/ranks/:id',
  battalionsCreate: '/api/battalions',
  battalionsUpdate: '/api/battalions/:id',
  battalionsDelete: '/api/battalions/:id',
  companiesCreate: '/api/companies',
  companiesUpdate: '/api/companies/:id',
  companiesDelete: '/api/companies/:id',
  trainingsCreate: '/api/trainings',
  trainingsUpdate: '/api/trainings/:id',
  trainingsDelete: '/api/trainings/:id',
  trainingRecordsCreate: '/api/training-records',
  trainingRecordsUpdate: '/api/training-records/:id',
  trainingRecordsDelete: '/api/training-records/:id',
  trainingCategoriesCreate: '/api/training-categories',
  trainingCategoriesUpdate: '/api/training-categories/:id',
  trainingCategoriesDelete: '/api/training-categories/:id',
  deploymentsCreate: '/api/deployments',
  deploymentsUpdate: '/api/deployments/:id',
  deploymentsDelete: '/api/deployments/:id',
  deploymentRecordsCreate: '/api/deployment-records',
  deploymentRecordsUpdate: '/api/deployment-records/:id',
  deploymentRecordsDelete: '/api/deployment-records/:id',
  engagementsCreate: '/api/engagements',
  engagementsUpdate: '/api/engagements/:id',
  engagementsDelete: '/api/engagements/:id',
  fileUpload: '/api/files/upload',
} as const
