export const SESSION_COOKIE_NAME = 'dms_session'
export const SESSION_DURATION_HOURS = 12
export const SESSION_TOKEN_HEADER_NAME = 'x-dms-session-token'

export const PERMISSION_CODES = {
  auditView: 'audit.view',
  rankView: 'rank.view',
  rankCreate: 'rank.create',
  rankDelete: 'rank.delete',
  personnelView: 'personnel.view',
  personnelCreate: 'personnel.create',
  personnelUpdate: 'personnel.update',
  personnelDelete: 'personnel.delete',
  battalionView: 'battalion.view',
  userCreate: 'user.create',
  userUpdate: 'user.update',
  userDelete: 'user.delete',
  accountTypeCreate: 'account_type.create',
  accountTypeUpdate: 'account_type.update',
  accountTypeDelete: 'account_type.delete',
  battalionCreate: 'battalion.create',
  battalionUpdate: 'battalion.update',
  battalionDelete: 'battalion.delete',
  companyView: 'company.view',
  companyCreate: 'company.create',
  companyUpdate: 'company.update',
  companyDelete: 'company.delete',
  trainingView: 'training.view',
  trainingCreate: 'training.create',
  trainingUpdate: 'training.update',
  trainingDelete: 'training.delete',
  trainingManage: 'training.manage',
  deploymentView: 'deployment.view',
  deploymentCreate: 'deployment.create',
  deploymentUpdate: 'deployment.update',
  deploymentDelete: 'deployment.delete',
  deploymentManage: 'deployment.manage',
  engagementView: 'engagement.view',
  engagementCreate: 'engagement.create',
  engagementUpdate: 'engagement.update',
  engagementDelete: 'engagement.delete',
  engagementManage: 'engagement.manage',
  equipmentView: 'equipment.view',
  equipmentCreate: 'equipment.create',
  equipmentUpdate: 'equipment.update',
  equipmentDelete: 'equipment.delete',
  equipmentManage: 'equipment.manage',
  equipmentIssue: 'equipment.issue',
  equipmentMaintain: 'equipment.maintain',
} as const
