import {
  EXTERNAL_FILE_ALLOWED_PROTOCOLS,
  FILE_UPLOAD_ALLOWED_SOURCE_TYPES,
  FILE_UPLOAD_MAX_SIZE_BYTES,
} from '../../../config/storage-s3'

export {
  EXTERNAL_FILE_ALLOWED_PROTOCOLS,
  FILE_UPLOAD_ALLOWED_SOURCE_TYPES,
  FILE_UPLOAD_MAX_SIZE_BYTES,
}
