import { createError, defineEventHandler, getQuery } from 'h3'
import type { RankListApiResponse } from '../../shared/responses'
import { PERMISSION_CODES, RANK_SEARCHABLE_FIELD_COLUMNS } from '../../shared/constants'
import { mapRankListItem, parseManagementPaginationQuery } from '../../shared/utils'
import { parsePersonnelAdvancedSearchConditions } from '../../shared/validations'
import { requirePermission } from '../../utils/auth/requirePermission'
import { buildPersonnelAdvancedSearchFilters } from '../../utils/personnel/buildPersonnelAdvancedSearchFilters'
import { getServiceSupabaseClient } from '../../utils/auth/serviceClient'
import { searchRank } from '../../utils/ranks/searchRank'
