import {
  EQUIPMENT_ASSET_SEARCHABLE_FIELD_COLUMNS,
  EQUIPMENT_CATEGORY_SEARCHABLE_FIELD_COLUMNS,
  EQUIPMENT_ISSUANCE_SEARCHABLE_FIELD_COLUMNS,
  EQUIPMENT_ITEM_SEARCHABLE_FIELD_COLUMNS,
} from '../../../../server/shared/constants'
