import {
  AcademicCapIcon,
  ArchiveBoxIcon,
  ArrowsRightLeftIcon,
  ArrowsUpDownIcon,
  BellIcon,
  BuildingOffice2Icon,
  ChartBarIcon,
  CheckCircleIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClipboardDocumentCheckIcon,
  ClipboardDocumentListIcon,
  ClockIcon,
  Cog6ToothIcon,
  CubeIcon,
  ExclamationTriangleIcon,
  EyeIcon,
  HomeIcon,
  InformationCircleIcon,
  MagnifyingGlassIcon,
  MapIcon,
  MapPinIcon,
  PencilSquareIcon,
  PlusIcon,
  QuestionMarkCircleIcon,
  ShieldCheckIcon,
  ShieldExclamationIcon,
  Squares2X2Icon,
  TableCellsIcon,
  TrashIcon,
  XCircleIcon,
  XMarkIcon,
  UsersIcon,
  UserPlusIcon
} from '@heroicons/vue/24/outline'
import type { Component } from 'vue'
import type { IconName } from '~/types/domain/misc'

export const HERO_ICON_MAP: Record<IconName, Component> = {
  'home': HomeIcon,
  'users': UsersIcon,
  'building': BuildingOffice2Icon,
  'clipboard': ClipboardDocumentCheckIcon,
  'clipboard-document-list': ClipboardDocumentListIcon,
  'academic-cap': AcademicCapIcon,
  'map': MapIcon,
  'map-pin': MapPinIcon,
  'shield': ShieldCheckIcon,
  'shield-exclamation': ShieldExclamationIcon,
  'squares': Squares2X2Icon,
  'table-cells': TableCellsIcon,
  'cube': CubeIcon,
  'archive': ArchiveBoxIcon,
  'arrow-path': ArrowsRightLeftIcon,
  'exclamation': ExclamationTriangleIcon,
  'chart-bar': ChartBarIcon,
  'check-circle': CheckCircleIcon,
  'information-circle': InformationCircleIcon,
  'question-mark-circle': QuestionMarkCircleIcon,
  'x-circle': XCircleIcon,
  'x-mark': XMarkIcon,
  'clock': ClockIcon,
  'cog': Cog6ToothIcon,
  'bell': BellIcon,
  'eye': EyeIcon,
  'pencil-square': PencilSquareIcon,
  'trash': TrashIcon,
  'arrows-up-down': ArrowsUpDownIcon,
  'magnifying-glass': MagnifyingGlassIcon,
  'chevron-up': ChevronUpIcon,
  'chevron-down': ChevronDownIcon,
  'chevron-left': ChevronLeftIcon,
  'chevron-right': ChevronRightIcon,
  'user-plus': UserPlusIcon,
  'plus': PlusIcon
}

export const getHeroIcon = (name: IconName): Component => HERO_ICON_MAP[name]
