import type { Ref } from 'vue'
import { RANK_FILTER_FIELD_OPTIONS } from '~/constants/page.constants'
import type { RankListQuery } from '~/types/domain/rank'
import { validateFields } from '~/utils/field-validation'
import { REGEX_PATTERNS } from '~/utils/regex'
