<template>
</template>

<script setup lang="ts">
import {
  DASHBOARD_METRICS,
  DASHBOARD_METRIC_CHANGE_CLASSES,
  DASHBOARD_METRIC_VALUE_CLASSES,
  DASHBOARD_METRICS_GRID_CLASSES,
  DASHBOARD_PAGE_SECTION_CLASSES,
  DASHBOARD_PAGE_SUBTITLE,
  DASHBOARD_PAGE_TITLE,
  DASHBOARD_PLACEHOLDER_CARDS,
  DASHBOARD_SECONDARY_GRID_CLASSES
} from '~/constants/page.constants'
</script>