export const AUTH_API_ENDPOINTS = Object.freeze({
  login: '/api/auth/login',
  logout: '/api/auth/logout',
  session: '/api/auth/session'
})

export const AUDIT_API_ENDPOINTS = Object.freeze({
  logs: '/api/audit/logs',
  search: '/api/audit/search',
  logById: (id: string) => `/api/audit/logs/${id}`,
  print: '/api/audit/print'
})

export const USER_MANAGEMENT_API_ENDPOINTS = Object.freeze({
  kpis: '/api/users/kpis',
  userProfiles: '/api/users',
  userProfilesSearch: '/api/users/search',
  userProfileById: (id: string) => `/api/users/${id}`,
  userProfilePassword: (id: string) => `/api/users/${id}/password`,
  userProfileActivation: (id: string) => `/api/users/${id}/activation`,
  accountTypes: '/api/account-types',
  accountTypesSearch: '/api/account-types/search',
  accountTypeById: (id: string) => `/api/account-types/${id}`,
  privileges: '/api/privileges',
})

export const UNIT_MANAGEMENT_API_ENDPOINTS = Object.freeze({
  kpis: '/api/units/kpis',
  battalions: '/api/battalions',
  battalionsSearch: '/api/battalions/search',
  battalionsSuggestions: '/api/battalions/suggestions',
  battalionById: (id: string) => `/api/battalions/${id}`,
  battalionPersonnel: (id: string) => `/api/battalions/${id}/personnel`,
  battalionEquipment: (id: string) => `/api/battalions/${id}/equipment`,
  battalionCompanies: (id: string) => `/api/battalions/${id}/companies`,
  battalionAssignPersonnel: (id: string) => `/api/battalions/${id}/assign`,
  companies: '/api/companies',
  companiesSearch: '/api/companies/search',
  companiesSuggestions: '/api/companies/suggestions',
  companyById: (id: string) => `/api/companies/${id}`,
  companyPersonnel: (id: string) => `/api/companies/${id}/personnel`,
  companyEquipment: (id: string) => `/api/companies/${id}/equipment`,
  companyAssignPersonnel: (id: string) => `/api/companies/${id}/assign`,
})

export const TRAINING_MANAGEMENT_API_ENDPOINTS = Object.freeze({
  kpis: '/api/trainings/kpis',
  trainings: '/api/trainings',
  trainingsSearch: '/api/trainings/search',
  trainingsSuggestions: '/api/trainings/suggestions',
  trainingById: (id: string) => `/api/trainings/${id}`,
  trainingCategories: '/api/training-categories',
  trainingCategoriesSearch: '/api/training-categories/search',
  trainingCategoryById: (id: string) => `/api/training-categories/${id}`,
  trainingRecords: '/api/training-records',
  trainingRecordsSearch: '/api/training-records/search',
  trainingRecordById: (id: string) => `/api/training-records/${id}`,
})

export const DEPLOYMENT_MANAGEMENT_API_ENDPOINTS = Object.freeze({
  kpis: '/api/deployments/kpis',
  deployments: '/api/deployments',
  deploymentsSearch: '/api/deployments/search',
  deploymentRecords: '/api/deployment-records',
  deploymentRecordsSearch: '/api/deployment-records/search',
  deploymentRecordById: (id: string) => `/api/deployment-records/${id}`,
  deploymentRecordByIdLocation: (id: string) => `/api/deployment-records/${id}/location`,
  deploymentByIdDetails: (id: string) => `/api/deployments/${id}/details`,
  deploymentByIdLocation: (id: string) => `/api/deployments/${id}/location`,
})

export const ENGAGEMENT_MANAGEMENT_API_ENDPOINTS = Object.freeze({
  kpis: '/api/engagements/kpis',
  engagements: '/api/engagements',
  engagementsSearch: '/api/engagements/search',
  engagementRecords: '/api/engagement-records',
  engagementRecordsSearch: '/api/engagement-records/search',
  engagementRecordById: (id: string) => `/api/engagement-records/${id}`,
  engagementById: (id: string) => `/api/engagements/${id}`,
  engagementPersonnel: (id: string) => `/api/engagements/${id}/personnel`,
})

export const EQUIPMENT_MANAGEMENT_API_ENDPOINTS = Object.freeze({
  equipmentCategories: '/api/equipment-categories',
  equipmentCategoriesKpis: '/api/equipment-categories/kpis',
  equipmentCategoriesSearch: '/api/equipment-categories/search',
  equipmentCategoriesSuggestions: '/api/equipment-categories/suggestions',
  equipmentCategoryById: (id: string) => `/api/equipment-categories/${id}`,
  equipmentCategoryItemsById: (id: string) => `/api/equipment-categories/${id}/items`,
  equipmentItems: '/api/equipment-items',
  equipmentItemsKpis: '/api/equipment-items/kpis',
  equipmentItemsSearch: '/api/equipment-items/search',
  equipmentItemsSuggestions: '/api/equipment-items/suggestions',
  equipmentItemById: (id: string) => `/api/equipment-items/${id}`,
  equipmentAssets: '/api/equipment-assets',
  equipmentAssetsSearch: '/api/equipment-assets/search',
  equipmentAssetsSuggestions: '/api/equipment-assets/suggestions',
  equipmentAssetsKpis: '/api/equipment-assets/kpis',
  equipmentAssetById: (id: string) => `/api/equipment-assets/${id}`,
  equipmentIssuances: '/api/equipment-issuances',
  equipmentIssuancesSearch: '/api/equipment-issuances/search',
  equipmentIssuanceById: (id: string) => `/api/equipment-issuances/${id}`,
})

export const DASHBOARD_API_ENDPOINTS = Object.freeze({
  unitManagementKpis: '/api/dashboard/unit-management',
  topKpis: '/api/dashboard/top-kpis',
  personnelDeploymentSummary: '/api/dashboard/personnel-deployment-summary',
  equipmentStatusOverview: '/api/dashboard/equipment-status-overview',
  criticalPersonnel: '/api/dashboard/critical-personnel',
  criticalEquipment: '/api/dashboard/critical-equipment',
  nearRotation: '/api/dashboard/near-rotation',
  locationLoadAnalysis: '/api/dashboard/location-load-analysis',
  personnelDeploymentHistory: '/api/dashboard/personnel-deployment-history',
  operationalTimeMonitoring: '/api/dashboard/operational-time-monitoring',
})

export const PERSONNEL_API_ENDPOINTS = Object.freeze({
  personnel: '/api/personnel',
  personnelKpis: '/api/personnel/kpis',
  personnelSearch: '/api/personnel/search',
  personnelSuggestions: '/api/personnel/suggestions',
  personnelBatchUpload: '/api/personnel/batch-upload',
  personnelById: (id: string) => `/api/personnel/${id}`,
  personnelTrainingRecords: (id: string) => `/api/personnel/${id}/training-records`,
  personnelDeploymentRecords: (id: string) => `/api/personnel/${id}/deployment-records`,
  personnelDeploymentRecord: (id: string) => `/api/personnel/${id}/deployment-record`,
  personnelEngagementRecords: (id: string) => `/api/personnel/${id}/engagement-records`,
  personnelEngagementRecord: (id: string) => `/api/personnel/${id}/engagement-record`,
  personnelTrainingRecord: (id: string) => `/api/personnel/${id}/training-record`,
  locations: '/api/personnel/locations',
  ranks: '/api/ranks',
  rankSuggestions: '/api/ranks/suggestions',
  rankById: (id: string) => `/api/ranks/${id}`,
})

export const FILE_MANAGEMENT_API_ENDPOINTS = Object.freeze({
  upload: '/api/files/upload',
})

export const APPLICATION_SETTINGS_API_ENDPOINTS = Object.freeze({
  settings: '/api/application-settings',
})

export const FILE_UPLOAD_CONSTRAINTS = Object.freeze({
  maxSizeBytes: 10 * 1024 * 1024,
  imageMimePrefixes: ['image/'],
})

export const AUTH_LOCAL_STORAGE_KEYS = Object.freeze({
  sessionToken: 'dms_session_token',
  sessionTokenExpiresAt: 'dms_session_token_expires_at',
  applicationSettings: 'dms_application_settings',
})

export const AUTH_HEADERS = Object.freeze({
  sessionToken: 'x-dms-session-token'
})

export const API_LOADING_MESSAGES = Object.freeze({
  authenticate: 'Signing in...',
  fetchSession: 'Validating session...',
  logout: 'Signing out...',
  fetchAuditLogs: 'Loading audit logs...',
  fetchAuditLogDetail: 'Loading audit log details...',
  fetchUserProfiles: 'Loading user profiles...',
  fetchUserAccounts: 'Loading user accounts...',
  fetchUserManagementKpis: 'Loading user management KPIs...',
  fetchPrivileges: 'Loading privileges...',
  createUserProfile: 'Creating user profile...',
  updateUserProfile: 'Updating user profile...',
  updateUserPassword: 'Updating user password...',
  updateUserActivation: 'Updating user status...',
  deleteUserProfile: 'Deleting user profile...',
  createAccountType: 'Creating account type...',
  updateAccountType: 'Updating account type...',
  deleteAccountType: 'Deleting account type...',
  fetchPersonnel: 'Loading personnel records...',
  fetchPersonnelKpis: 'Loading personnel KPIs...',
  fetchPersonnelDetails: 'Loading personnel profile...',
  createPersonnel: 'Creating personnel record...',
  uploadPersonnelBatch: 'Uploading personnel batch...',
  updatePersonnel: 'Updating personnel record...',
  deletePersonnel: 'Deleting personnel record...',
  fetchRanks: 'Loading rank records...',
  createRank: 'Creating rank record...',
  deleteRank: 'Deleting rank record...',
  fetchBattalions: 'Loading battalion records...',
  fetchCompanies: 'Loading company records...',
  fetchUnitManagementPageKpis: 'Loading unit page KPIs...',
  fetchUnitManagementKpis: 'Loading unit KPIs...',
  fetchDashboardTopKpis: 'Loading dashboard top KPI cards...',
  fetchDashboardPersonnelDeploymentSummary: 'Loading dashboard personnel deployment summary...',
  fetchDashboardEquipmentStatusOverview: 'Loading dashboard equipment status overview...',
  fetchDashboardCriticalPersonnel: 'Loading dashboard critical personnel...',
  fetchDashboardCriticalEquipment: 'Loading dashboard critical equipment...',
  fetchDashboardNearRotation: 'Loading dashboard near-rotation alerts...',
  fetchDashboardLocationLoadAnalysis: 'Loading dashboard location load analysis...',
  fetchDashboardPersonnelDeploymentHistory: 'Loading dashboard personnel deployment history...',
  fetchDashboardOperationalTimeMonitoring: 'Loading dashboard operational time monitoring...',
  createBattalion: 'Creating battalion record...',
  updateBattalion: 'Updating battalion record...',
  deleteBattalion: 'Deleting battalion record...',
  createCompany: 'Creating company record...',
  updateCompany: 'Updating company record...',
  deleteCompany: 'Deleting company record...',
  assignBattalionPersonnel: 'Assigning personnel to battalion...',
  assignCompanyPersonnel: 'Assigning personnel to company...',
  fetchTrainings: 'Loading training records...',
  fetchTrainingManagementKpis: 'Loading training KPIs...',
  fetchTrainingRecords: 'Loading training records...',
  fetchTrainingCategories: 'Loading training categories...',
  createTraining: 'Creating training record...',
  updateTraining: 'Updating training record...',
  deleteTraining: 'Deleting training record...',
  createTrainingRecord: 'Creating training personnel record...',
  updateTrainingRecord: 'Updating training personnel record...',
  deleteTrainingRecord: 'Deleting training personnel record...',
  createTrainingCategory: 'Creating training category...',
  updateTrainingCategory: 'Updating training category...',
  deleteTrainingCategory: 'Deleting training category...',
  fetchTrainingPersonnel: 'Loading assigned training personnel...',
  fetchTrainingSuggestions: 'Loading training suggestions...',
  fetchDeployments: 'Loading deployments...',
  fetchDeploymentManagementKpis: 'Loading deployment KPIs...',
  fetchDeploymentRecords: 'Loading deployment records...',
  createDeployment: 'Creating deployment record...',
  updateDeployment: 'Updating deployment record...',
  deleteDeployment: 'Deleting deployment record...',
  fetchEngagements: 'Loading engagements...',
  fetchEngagementManagementKpis: 'Loading engagement KPIs...',
  fetchEngagementRecords: 'Loading engagement records...',
  updateEngagement: 'Updating engagement record...',
  deleteEngagement: 'Deleting engagement record...',
  fetchEngagementPersonnel: 'Loading engagement personnel...',
  createEngagement: 'Creating engagement record...',
  createEngagementRecord: 'Creating engagement personnel record...',
  updateEngagementRecord: 'Updating engagement personnel record...',
  deleteEngagementRecord: 'Deleting engagement personnel record...',
  uploadFile: 'Uploading file...',
  fetchEquipmentCategories: 'Loading equipment categories...',
  fetchEquipmentCategoryKpis: 'Loading equipment category KPIs...',
  fetchEquipmentCategorySuggestions: 'Loading equipment category suggestions...',
  createEquipmentCategory: 'Creating equipment category...',
  updateEquipmentCategory: 'Updating equipment category...',
  deleteEquipmentCategory: 'Deleting equipment category...',
  fetchEquipmentItems: 'Loading equipment items...',
  fetchEquipmentItemKpis: 'Loading equipment item KPIs...',
  createEquipmentItem: 'Creating equipment item...',
  updateEquipmentItem: 'Updating equipment item...',
  deleteEquipmentItem: 'Deleting equipment item...',
  fetchEquipmentAssets: 'Loading equipment assets...',
  fetchEquipmentAssetKpis: 'Loading equipment asset KPIs...',
  createEquipmentAsset: 'Creating equipment asset...',
  updateEquipmentAsset: 'Updating equipment asset...',
  deleteEquipmentAsset: 'Deleting equipment asset...',
  fetchEquipmentIssuances: 'Loading equipment issuances...',
  createEquipmentIssuance: 'Creating equipment issuance...',
  updateEquipmentIssuance: 'Updating equipment issuance...',
  deleteEquipmentIssuance: 'Deleting equipment issuance...',
  fetchApplicationSettings: 'Loading application settings...',
  updateApplicationSettings: 'Updating application settings...',
})
