import { createError } from 'h3'
import type { SupabaseClient } from '@supabase/supabase-js'
import { RANK_LIST_SELECT_COLUMNS } from '../../shared/constants'
import type { PersonnelSearchFilter, RankRow } from '../../shared/models'
import { applyPersonnelSearchFilters } from '../../shared/utils'
