import type {
  EquipmentAssetRow,
  EquipmentIncidentRow,
  EquipmentItemRow,
} from '@/server/shared/models'

export const equipmentItemFixture: EquipmentItemRow = {
  id: 'item',
  equipment_code: 'EQ-01',
  category_id: 'category',
  name: 'Radio',
  model: null,
  manufacturer: null,
  description: null,
  unit_of_measure: 'unit',
  minimum_stock_level: 0,
  is_serialized: true,
  is_active: true,
  created_at: 'created',
  updated_at: 'updated',
  category: { id: 'category', code: 'COMMS', name: 'Communications' },
}

export const equipmentAssetFixture: EquipmentAssetRow = {
  id: 'asset',
  asset_tag: 'AS-01',
  equipment_item_id: 'item',
  serial_no: null,
  batch_no: null,
  procurement_date: null,
  acquisition_cost: 0,
  fund_source: null,
  current_location: null,
  condition_status_id: null,
  serviceability_status_id: null,
  asset_status_id: 'status',
  remarks: null,
  created_at: 'created',
  updated_at: 'updated',
  equipment_item: { id: 'item', equipment_code: 'EQ-01', name: 'Radio' },
  condition_status: null,
  serviceability_status: null,
  asset_status: { id: 'status', name: 'Available' },
}

export const incidentFixture: EquipmentIncidentRow = {
  id: 'incident',
  incident_no: 'IN-01',
  equipment_asset_id: 'asset',
  personnel_id: null,
  deployment_id: null,
  incident_type_id: 'type',
  incident_date: '2026-10-04',
  location: null,
  location_latitude: null,
  location_longitude: null,
  description: 'Damage',
  investigation_status_id: null,
  resolution: null,
  remarks: null,
  created_at: 'created',
  updated_at: 'updated',
  equipment_asset: null,
  personnel: null,
  deployment: null,
  incident_type: null,
  investigation_status: null,
}
