import type { ApplicationSettingsRow } from '@/server/shared/models'

export const settingsRowFixture: ApplicationSettingsRow = {
  id: 'settings',
  singleton_key: 'default',
  app_name: 'AFP Monitoring',
  app_short_code: 'AFP',
  app_description: null,
  default_timezone: 'Asia/Manila',
  default_locale: 'en-PH',
  default_date_format: 'yyyy-MM-dd',
  default_time_format: '24h',
  app_theme: 'emerald',
  density_mode: 'comfortable',
  page_size: 10,
  map_default_latitude: 14.6,
  map_default_longitude: 121,
  map_default_zoom: 10,
  map_min_zoom: 1,
  map_max_zoom: 22,
  personnel_code_prefix: 'AFP',
  equipment_asset_code_prefix: 'ASSET',
  enable_audit_log_retention: true,
  audit_log_retention_days: 365,
  enable_incident_notifications: true,
  enable_equipment_maintenance_reminders: true,
  created_at: '2026-10-04T00:00:00Z',
  updated_at: '2026-10-04T00:00:00Z',
}
